export const SET_ALL_LOCATIONS = "SET_ALL_LOCATIONS";
export const CREATE_NEW_LOCATION = "CREATE_NEW_LOCATION";
export const FILTER_BY_ADDRESS = "FILTER_BY_ADDRESS"
export const GET_LOCATION = "GET_LOCATION"
export const SET_LOCATION_ID = "SET_LOCATION_ID"
export const RESET_LOCATION = "RESET_LOCATION"